### ISSUE TITLE
Channel Ideas

### ISSUE THREAD

**Issue by gonzo90017** [fnord12/script.pseudotv#14]
I've never been able to get **Best Effort Scheduling** to work. From some old posts it seems it was a pain for the developers to add the feature and it seems very few users were able to get it working properly.

I think a simpler method would be if you could add 
**Best Day Scheduling**

For example. I have a lot of Saturday morning cartoons which don't fit in any daily channel since most of them only lasted 1 or 2 seasons. Most are only 13-26 episodes long. 

This is how it would work:
Let's say I have 2 channels. 
Ch 2: **Boomerang**
Ch 19: **Boomerang Weekend**

For Ch 19:
Advanced Settings
Take over Channel: 2
Day: Saturday, Sunday
(and of course any other rules like pause when not watching :)

So **Boomerang** would turn into **Boomerang Weekend** for Saturday and Sunday.
Monday-Friday **Boomerang** would return.

Another idea, **Holiday Channels**.
You would create channels that would only show up at certain times of the year. Say a Halloween channel that would only show up in the month of October. A thanksgiving channel that would only show up in November. A Christmas channel that would only show up in December. You get the point.

**Comment by fnord12** [comment]
Another Advanced Rule area where the code is beyond me.  The basic concept is a lot like interleaving, so it probably does work if we could just figure out what inputs it is looking for.   I spent some time looking at the code and trying to override a channel based on the day of the week, but it didn't take.

I suppose as you suggest i could scrap the current code and try to write my own thing entirely; i'm just not sure it's worth the effort.  I have an Aftertoons channel that just runs all day.  I have a Christmas channel that i just manually activate in December.   It's good enough for me!

I'll keep the idea in mind but it's unlikely i'll address any time soon.

**Comment by gonzo90017** [comment]
Maybe a simpler option would work?
**Hide a channel**
You choose what days the  channel is hidden. Say Monday-Friday?

But don't waste too much time if these ideas aren't possible. I appreciate all the bugs you've been fixing. I'm surprised the 1st interleave channel bug was finally fixed. Where your first interleave channel would change the starting episode to a random number even when setting it to 1. This one bugged me for many years!

Before I forget. Is it even possible to create movie channel. That gives you the option to start the movie from the beginning?
Say you select a movie channel where the movie is halfway through. And you get a popup asking if you would like to watch the movie from the start. This is the only thing that's stopped me from adding movie channels in PseudoTV. Since most of the movies I have in my computer I have yet to watch.

**Comment by fnord12** [comment]
gonzo90017, regarding your Start From Beginning request, i've been meaning to test this but kept forgetting.  But now i've confirmed: pressing 0 and then Enter should cause any video to scan to the beginning.  So you shouldn't need a special popup.

**Comment by gonzo90017** [comment]
Just tried it and it works! Only issue is that the EPG pops up after pressing Enter. But I guess I can live with it :)

Is there any way to get Genre colors working in the guide?I love the way WMC does it. Where movies are purple, sports are green, and cartoons are blue. If possible an option to pick a color for each channel individually.

**Comment by fnord12** [comment]
I've added the EPG color options for 4.5.2.

I don't know why the EPG pops up after pressing enter.  It doesn't for me.  But i guess it's not a big deal if you're ok with it.

Hey, in the future, please put requests into separate issues so that they can be tracked and closed!  :-)

**Comment by gonzo90017** [comment]
Thanks for the update.

A couple of small requests. Can we get genre colors working for Directory channels and Paused channels?

Also. Blue and Purple look great. But green seems to be a bit overwhelming and makes it hard to see the text. Can we maybe change it to another color? Doesn't really matter which one it is as long as it's readable :)

**Comment by fnord12** [comment]
Thanks for the feedback.  The green looked fine to me but it probably looks different on different devices.  I've replaced it with a different green.  If this one's no good either, can you take a crack at modifying the file under \resources\skins\default\media\pstvButtonNoFocusAlt3.png (or the Estuary version if you're using that skin) and then either paste it back here or give me the hex numbers?

I've also added support for the colors for when paused or if using the longblock option.

**Comment by gonzo90017** [comment]
Awesome. Nice to know I can modify the color if I need to.
