### ISSUE TITLE
4.5.1

### ISSUE THREAD

**Issue by fnord12** [fnord12/script.pseudotv#18]
Just a note: I've had version 4.5.1 as a release candidate for a few weeks now to see if any bugs shook out.  I've now merged it into the master branch.  See the Release Notes for details on new features & fixes.  I've also updated the ReadMe to reflect the new features and added some other tips & tricks.  If you're having trouble, see the Troubleshooting document for instructions on how to provide me with a debug log.

**Comment by psicotron3** [comment]
Just to give feedback. I've used the version 4.5.1 without any issue for the whole weekend. The options to use a default duration for worked great on some videos that never worked with directory channels before. Thanks.

**Comment by fnord12** [comment]
Glad to hear it.  Thanks for taking the time to give feedback!
