### ISSUE TITLE
PTV not picking up custom playlist

### ISSUE THREAD

**Issue by undecomposed** [fnord12/script.pseudotv#20]
If I create a smart playlist and set a channel to it (channel 27/100), the channel is not created.

I tried resetting all channels, and also making the playlist as short as I can (a single TV show, 31 episodes total).

Which logs do I gather to submit them?

Also, limit of playlist items is set to 25 for me. Does that affect the channel not being added?

**Comment by fnord12** [comment]
Make sure the custom playlist is of Type Episodes, not Type TVShow.

If that doesn't help can you also try creating a playlist of Type Movie just to see if that will work?  Also if you're using SMBs or something, can you try just creating a simple playlist with local files?  Also try to avoid "special" characters in the filenames for the test.

The Playlist Media Limit doesn't apply to custom playlists, which instead use the Limit To field in the playlist itself.   In any event the media limit is applied per channel, so it shouldn't cause a channel to not get populated.  

If it's not the Type issue, i guess i'll need a log.  Please enable debugging and then restart Kodi (this allows me to see the system info and version numbers that get logged when Kodi starts), and then set PseudoTV to do a forced reset, and then start PseudoTV.  Details on how to get and submit the log are linked to from the Troubleshooting.md doc.

**Comment by undecomposed** [comment]
God-friggin-dammit. Yes, it was the list type. How could I miss that /facepalm.

Is this in the README? I don't think I saw that. If not, can I update the README with this?

**Comment by fnord12** [comment]
Glad it was an easy fix!

My goal is to update the Troubleshooting doc with some common problems.  I'll make sure this is included.
