### ISSUE TITLE
Some channels not working correctly with Custom Playlists

### ISSUE THREAD

**Issue by ghost** [fnord12/script.pseudotv#24]
I've created a number of Custom Playlists through the Kodi interface to be used as channels in PseudoTV. Within Kodi, they work correctly - they populate based off the parameters I set and I can see a list of movies when viewing/watching the playlist.

However, I'm having issues when trying to configure some of them in PseudoTV via the channel settings.

I choose the option to specify a custom playlist for the channel, and when I select a valid, existing playlist, it shows as blank as if I hadn't selected anything. Sometimes I am able to save and exit and view the channel I had just created (although the channel remains nameless - even if I set a name through the rules), other times it is as if I never created the channel.

Sometimes when I select the playlist, the channel configuration immediately exits and it kicks me to the primary PseudoTV settings interface.

I'm happy to provide any additional details or files that might help get this problem resolved. This is a great add-on and I'm super appreciative that it's still being maintained!

**Comment by ghost** [comment]
Wow, I'm so sorry - it turns out this was happening because not all of my Kodi playlists were named. Assigning them names seems to have resolved the issue.

**Comment by fnord12** [comment]
Sorry i had been offline for the past couple of days.  Glad you were able to find a solution!
