### ISSUE TITLE
Wrong Info when changing channels

### ISSUE THREAD

**Issue by gonzo90017** [fnord12/script.pseudotv#27]
When switching channels the information popup always has the wrong info. The weird thing is that the artwork is always correct:
![wrong](https://user-images.githubusercontent.com/24837361/98459714-35e27300-2152-11eb-8ecf-eb5082afad71.jpg)

The only way it shows the correct information is by pressing the info button on my remote:
![Correct](https://user-images.githubusercontent.com/24837361/98459716-3844cd00-2152-11eb-80e6-bc368ab1b8de.jpg)

This one is pretty easy to replicate. It happens if I switch channels by selecting it from the guide or pressing up and down on my remote.

**Comment by fnord12** [comment]
Just pushed a patch that fixed this issue.
