### ISSUE TITLE
Hiding Short Videos in EPG

### ISSUE THREAD

**Issue by gils001** [fnord12/script.pseudotv#3]
Hi, I'm having a minor issue with my EPG. I am interleaving a directory channel consisting of various short videos < 360 seconds and I have the option to "Hide short videos" enabled. While the short videos do not show up in the actual guide (the timeslots) they do show up in the show info below the EPG.  For example, say I've highlighted an episode of Looney Tunes but the info below the guide shows "no info" and a directory location for the upcoming short video that I am interleaving.

**Comment by fnord12** [comment]
Yeah it turns out there was never an attempt in the code to hide the short videos from the Info box (only the EPG itself).  I've added it.  I'm slightly paranoid that it's somehow introduced a performance lag on the EPG; let me know if you notice anything.  (I DID learn that if you have a channel of only short videos and you have Hide Short Videos turned on, it adds considerable lag to the EPG.)

**Comment by gils001** [comment]
> Yeah it turns out there was never an attempt in the code to hide the short videos from the Info box (only the EPG itself). I've added it. I'm slightly paranoid that it's somehow introduced a performance lag on the EPG; let me know if you notice anything. (I DID learn that if you have a channel of only short videos and you have Hide Short Videos turned on, it adds considerable lag to the EPG.)

I think this may be dependent on certain use cases. I have enabled the "Don't play this channel" advanced setting for my directory channel and it doesn't show up on the EPG. I don't notice any significant performance lag for my particular setup. Oddly enough, though you resolved the issue of short videos showing up in the info box, I encounter similar behavior with other channels. For example, say I scroll above/down my current selection and return to my prior selection, it will show info for another show and not the show I'm highlighting and the same can be said while I'm scrolling horizontally too.

**Comment by fnord12** [comment]
Can you confirm - are you saying that the incorrect info for other channels is something newly introduced, or a problem you've always had.  I'm not seeing any problems there.

I do occasionally have a problem with very short videos when they're NOT hidden - they'll show in the EPG but not in the info window (kind of the opposite of the problem you originally reported).  I learned yesterday that has to do with the way the EPG is coded; there's potentially a rounded issue there.  The way PSTV determines what should appear in the EPG info window seems overly complicated and i was wondering if i could give it an overhaul.  It didn't seem worth it for my short video problem but if others are also having problems i may take a look.

**Comment by gils001** [comment]
![Kodi_20200531_141334](https://user-images.githubusercontent.com/63884407/83362883-b1412c80-a349-11ea-8f5b-5de9da9aee24.png)

It seems as though this is a new problem because I tried this on Steve's branch and it did not show up, but I did notice a reoccurring pattern. Say I'm on "Justice League" Channel 54 and move to the next selection horizontally "Regular Show" which is significantly shorter, it will show the longer show's info and not the shorter one. Similarly, say I'm highlighting "Mobile Suit Gundam Wing" channel 55 and move vertically above to "Regular Show", it will again show the longer show's info. Really strange because it does this with channels that are not interleaved and are set to "TV Network" type as well as channels with interleaved videos. This was observed on my Android TV box.

**Comment by fnord12** [comment]
Is it possible you have short videos on the non-interleaved channels too?  I think what is happening is that you are passing over "invisible" channels.  I told it not to display info for the very short channels (when that mode is enabled) and so it's retaining the info of the last show that it was allowed to show info for.

I think i'll need to back out this update, since it looks like it can get very complicated.

**Comment by gils001** [comment]
> Is it possible you have short videos on the non-interleaved channels too? I think what is happening is that you are passing over "invisible" channels. I told it not to display info for the very short channels (when that mode is enabled) and so it's retaining the info of the last show that it was allowed to show info for.
> 
> I think i'll need to back out this update, since it looks like it can get very complicated.

I apologize.. I rechecked and it seems as though this IS occuring for only interleaved channels. I set up a new non interleaved TV Network channel and the behavior does not occur.

**Comment by fnord12** [comment]
Hey  gils001.  Regarding this issue, see the comments in my release notes for 4.5.1.  

I've left 4.5.1 as a separate branch right now, to see if any bugs shake out that i didn't catch.  This allows the master branch to serve as a stable release.

**Comment by gils001** [comment]
> Hey gils001. Regarding this issue, see the comments in my release notes for 4.5.1.
> 
> I've left 4.5.1 as a separate branch right now, to see if any bugs shake out that i didn't catch. This allows the master branch to serve as a stable release.

I'll give it a look and see if there are any issues with this release. Thanks again for checking out my initial issue as well. I'm excited to add some plots for my directory channels. I'm going to close this issue as I feel you addressed my problems with a separate branch 4.5.1.
