### ISSUE TITLE
Kodi subtitle menu/controls?

### ISSUE THREAD

**Issue by trebory6** [fnord12/script.pseudotv#32]
Hi there! Love this, and thank you @fnord12 for keeping this up to date. I would definitely subscribe to a patreon or something similar for this if I could. 

One thing I noticed off the bat is how the Subtitle menu is gone, and all Kodi subtitle shortcut keys are missing and not working. T toggle for subtitles doesn't work, and the menu to get to subtitles also doesn't work.

What I did notice was that if I had enabled subtitles for that show/movie in Kodi outside of using PsuedoTV they do show up. So subtitles DO work, it's the menu/shortcut keys that don't work. 

I would love for that functionality to work again, and was hoping it was a simple fix since Subtitles themselves work, but it just seems that the shortcut keys and menu has been disabled. 

Thanks!

**Comment by fnord12** [comment]
Doing this strictly not for profit but i'm glad you're enjoying it!

The subtitle shortcut key works for me.  One thing may be that for PSTV the shortcuts have to be in the Global section, not Fullscreenvideo.  So here is a sample of my keymap.xml file:

```
<keymap>
    <global>
        <keyboard>
           
	        <n>AudioNextLanguage</n>
	        <n mod="ctrl">AudioDelayPlus</n>
	        <b mod="ctrl">AudioDelayMinus</b>
			
	        <l>NextSubtitle</l>
	        <l mod="alt">ShowSubtitles</l>
	        <l mod="ctrl">SubtitleDelayPlus</l>
	        <k mod="ctrl">SubtitleDelayMinus</k>

                <i mod="ctrl">ActivateWindow(videoosd)</i>
	        
		<c>RunScript(script.openinfowindow)</c>  
	        
	</keyboard>
  </global>
</keymap>
```

All of those shortcuts work for me in PSTV, so you may want to see how yours are different.  You'd also want to make sure that nothing is conflicting with your button (looks like you're using T, which i use to open tag overview).  I use N for Next Audio and L for subtitLe.

Also, the Control-I shortcut opens the standard Kodi OSD screen which PSTV normally suppresses.  That should then get you access to the subtitle UI, but that's a lot of clicks.

You may also be interested in my Autosub addon (or the fuller Language Preference Manager that I started from), which for me usually enables the subtitles i want automatically so i don't have to constantly press the buttons as i change channels.

(I also include C button shortcut to promote my script.openinfowindow, which lets me see the Cast list in PSTV.)

Let me know how it goes.

**Comment by trebory6** [comment]
Ah! Thanks for all the info! Turns out that "C" works to bring up the audio and subtitle menus, so that's been working great for now. 

I might figure out what's wrong with my other shortcuts, however everything seems to be working well for now. 

Thanks for the response, and thank you for keeping this alive!
