### ISSUE TITLE
m3u playlists

### ISSUE THREAD

**Issue by n4tur3502** [fnord12/script.pseudotv#34]
Is there a way to create a channel from m3u playlists synced from plexkodiconnect? All i can see are the xsp ones from kodi.

**Comment by fnord12** [comment]
PseudoTV actually generates .m3u files to use (or converts Kodi's xsp files if using Kodi playlists to create channels).   You can find them at \userdata\addon_data\script.pseudotv\cache .   I don't know about plexkodiconnect, but maybe you can try dropping one in or massaging it into that format?

**Comment by fnord12** [comment]
No response after a month so i'm closing this.  But don't hesitate to let me know if i can help.
