### ISSUE TITLE
Channel logo

### ISSUE THREAD

**Issue by wyild1** [fnord12/script.pseudotv#35]
Hi!

Is Channel Logo same as Channel watermark?  I can get the logo to apear on the EPG, but the watermark is still just the pseudoTV logo and not the channel logo

**Comment by wyild1** [comment]
Ahh ok.  I tried using a NFS folder and didnt work.  Pointed it back to a local folder and its working

This can be closed 

Cheers!

**Comment by fnord12** [comment]
Glad you were able to get it working!
