### ISSUE TITLE
Interleaving 3 commercial channels at once (Not an issue, just a thanks!)

### ISSUE THREAD

**Issue by momaw627** [fnord12/script.pseudotv#36]
Hey!  I'm the guy who messaged you through Soundcloud :)

I think I figured out my issue with the interleaved directory not pulling videos at random.  I was forgetting to rebuild my playlists after changing.

Here's how my commercial directory and interleaved channel look now:

Directory: Commercials (200)
Rule 1: Don't Play Channel
Rule 2: Force Random Mode (which I'm assuming does just that, randomizes the videos within the directory?)

Interleaved Channel: Kid's TV
Chan: 200  Min:1   Max:1   Start:5
Chan: 200  Min:2  Max:2   Start:10
Chan: 200  Min:3  Max:3   Start 15

This set up allows my Kid's TV channel to play an episode (of Scooby Doo, of course) and then interleave 3 different commercials from my commercials directory after every episode.

My original attempt was to set Starting Episode at 1, 2, and 3 but that resulted in the same commercials being played in succession with the oldest falling off every go around.

Seems to be working so far...  

I'm sure I'll be back with more questions as I delve deeper in. 

Thanks again for the fork and helping make a long time dream of mine come to fruition... the ability to have my own cable tv setup with only the things I like!

Beau

**Comment by fnord12** [comment]
I'm glad this is working for you.  And i guess if that's the case, you can just leave it alone.  But the interleave values for Start look wrong to me.  The Start value is supposed to control how long it takes before the interleaving begins.  Which means for your settings it should be playing 5 episodes of Scooby Doo before it begins to show commercials, and then only one commercial at a time until 10 videos (including commercials) play, etc..  Imo you shouldn't have to specify the Start value at all, or leave it at 1 (for all three) if you want to make sure that an actual episode plays first.

However, things sometimes behave a bit mysteriously when there are multiple rules being applied at once so, again, if what you have is working, might as well leave it.

You're correct on the purpose of the Force Random setting as well.

I'll leave this thread open for a while in case you do have more questions.
