### ISSUE TITLE
4:3 Channel Bug Placement

### ISSUE THREAD

**Issue by XeXoasz** [fnord12/script.pseudotv#39]
Hi everyone and fnord, 
I'm enjoying the app so far but the only problem I have is the channel bug logos I have are only in the 16:9 format. Theres a lot a content in 4:3 I have and would like the logos to be 4:3 instead. Possibly for individual channels, based on the content type (4:3 or 16:9) or for all whichever. I know the app isn't updated anymore but is there a way to change this in a xml file settings? 

Regardless, thanks in advance. Been trying to figure this out for a while now. 
@fnord12

**Comment by XeXoasz** [comment]
I tried adding the following code to script.pseudotv.TvOverlay.xml but it doesn't work. <control type="image" id="103" posX="1170" posY="590">
  <description>Channel Bug</description>
  <width>161</width>
  <height>109</height>
  <aspectratio>keep</aspectratio>
  <visible>Player.HasVideo + ![Player.Seeking | Player.Paused | Player.Forwarding | Player.Rewinding | Player.IsTempo]</visible>
  <animation effect="fade" end="20" condition="False">conditional</animation>
  <align condition="System.IntegerCompare(Player.VideoAspectY, 3) = 0">right</align>
  <aligny condition="System.IntegerCompare(Player.VideoAspectY, 3) = 0">bottom</aligny>
  <align condition="System.IntegerCompare(Player.VideoAspectY, 3) != 0">right</align>
  <aligny condition="System.IntegerCompare(Player.VideoAspectY, 3) != 0">bottom</aligny>
</control>

Is there really no other way to have the logo changed based on the aspect ratio? I tried info labels but it was giving me errors and I'm not sure how to implement it onto pseudotv. Where the heck does this go and how do I fix the logo aspect ratio issue? Just losing hope here..

**Comment by fnord12** [comment]
I think you found the script.pseudotv.TVOverlay.xml which specifies where the bug/logo goes and you can manipulate that for position.   I think the way to do what you want would be with conditional visibility, where you have two versions of the control tag set, one for each aspect ratio.   The problem is that I don't think Kodi's skinning engine has a condition that works for aspect ratio ( https://kodi.wiki/view/List_of_boolean_conditions#VideoPlayer ).   What you might try instead is just separating channels by type (e.g. TV shows are generally 4:3 and so you could use a 4:3 logo for those, and a 16:9 logo for movie channels.   To be honest I haven't really given it much thought and the logos have always seemed fine to me regardless of the aspect ratio so I may not be understanding what you're trying to do .  But yeah, it's more in the Kodi skinning parameters than in the PseudoTV code.

**Comment by XeXoasz** [comment]
> I think you found the script.pseudotv.TVOverlay.xml which specifies where the bug/logo goes and you can manipulate that for position. I think the way to do what you want would be with conditional visibility, where you have two versions of the control tag set, one for each aspect ratio. The problem is that I don't think Kodi's skinning engine has a condition that works for aspect ratio ( https://kodi.wiki/view/List_of_boolean_conditions#VideoPlayer ). What you might try instead is just separating channels by type (e.g. TV shows are generally 4:3 and so you could use a 4:3 logo for those, and a 16:9 logo for movie channels. To be honest I haven't really given it much thought and the logos have always seemed fine to me regardless of the aspect ratio so I may not be understanding what you're trying to do . But yeah, it's more in the Kodi skinning parameters than in the PseudoTV code.

Thank you for the reply but would you also be able to let me know which spots in the xml code will change the position? If I know the general area I could try to see how to change the position instead of trying to do it for each video content. Then if there's a way to specify which channels is 4:3 logo and which 16:9 is also good, but I was mainly looking for the area in the code that tells it where it's positioned. At the bottom I tried adding my own positions but it didn't change anything. Just changing it to a 4:3 position is good enough for me if any.

**Comment by XeXoasz** [comment]
@fnord12 Just changing it's position to fit closer to the 4:3 aspect ratio video is good enough for me. However I don't know which in the xml determines the position, and when I researched a solution someone added </ posx> 450r </ posx> under the description channel bug position  spot. When I did that, the logo didn't change positions. Is there another area in the code that already determines the corner's position and if so where/what is the code? Thanks

**Comment by XeXoasz** [comment]
@fnord12 so how do I change the position in the Overlay xml? I appreciate your comment but it didn't really solve anything. If you know where the position is determined and how to change it please let me know, thanks

**Comment by XeXoasz** [comment]
Dang. Guess I'm giving up on the feature, seems like a lack of interest

**Comment by XeXoasz** [comment]
Issue closed, i added a new update that allows 4:3 channel bug positions and labeled the old ones 16:9
