### ISSUE TITLE
Skins?

### ISSUE THREAD

**Issue by bornagainpenguin** [fnord12/script.pseudotv#40]
I recently downgraded to LibreELEC 9.2.6 in order to regain access to this addon.  Is there any way to get the old skins working for it?  I mean like Concast and some of the others here:

https://github.com/tromyl/PseudoTV_Skins

**Comment by fnord12** [comment]
Anything outside my my code package will definitely need an update to account for the new rowcount options.   The 4.5.2 release notes talk a little about how you need to modify a customized skin to make it work with my updates.   I don't know for sure if those skins will work but that's where i'd start.

**Comment by bornagainpenguin** [comment]
I admit that I am not a programmer, but also that I have been using this addon or a variation of it for a very long time over the years.  But I seem to recall it possible to do this without too much modification.  I'd have to hunt through the old threads on the Kodi Forums to be sure or not though.

Thanks for the replies.
