### ISSUE TITLE
PseudoTV isn't properly blocking Trakt from scrobbling during playback

### ISSUE THREAD

**Issue by bornagainpenguin** [fnord12/script.pseudotv#42]
I am using PseudoTV version 4.5.3 and Trakt version 3.2.6.  In Trakt I have in settings marked exclusions for Live TV, HTTP sources, Plugins, and Allow script exclusions.  Unfortunately it doesn't seem to matter.  When playing episodes of content in the PseudoTV interface, if I switch channels I get a message pop up over the screen to rate media that I literally only sampled a few moments of.  I have the option to reset watched status on for a reason.

I fully intend to mention this to the Trakt addon developer but since I am running an older version of the addon (because Leia) I don't know how much help that will be.  Hoping there is something I missed somewhere that will make it an easy fix.

Thanks again for everything.

**Comment by fnord12** [comment]
Sorry i'm not really actively supporting this anymore and i don't know anything about Trakt.   PsTV uses the regular Kodi player to play the videos and then Reset Watch literally sets the watch status back to what it was before PsTV starts, so i guess i can see why Trakt's script exclusion isn't working.  Disabling the Trakt add-on while you run PsTV may be the only way but i know that sounds awful.

**Comment by bornagainpenguin** [comment]
Yeah that's totally not an optimal manner of handling things.

Only I swear that this was not an issue before with this branch of the PseudoTV addon...so something has changed or I am not setting things properly.

I apologize for spamming the github repo, I was under the impression that you were still supporting the addon, just only on Kodi 18.x  I didn't realize that you were done with it.

**Comment by fnord12** [comment]
I still use this version all the time and can help people with basic install/use problems but i don't have time to update the code or help troubleshoot interactions with other addons/skins that i don't use.   Sorry i'm not more help!

**Comment by bornagainpenguin** [comment]
Oh!  Okay, that's perfectly fair.  I thought you were saying that you had also quit using it.  That's a horse of a different color if you simply don't have time to run down things that you're not actually using.  I completely understand that.

Thanks again and I apologize for the misunderstanding on my part.
