### ISSUE TITLE
Colored EPG blocks isn't working

### ISSUE THREAD

**Issue by XeXoasz** [fnord12/script.pseudotv#45]
Hey everyone 

When I try to do the alternate color for the EPG they don't end up switching right. I try the default one with the example and also some color codes I found online.

 Don't know if I need a specific code for it but I'd like the 3 color block images from source code, blue green and purple. 

If anyone knows the setup for the color code or if I'm doing something incorrectly let me know here. 

Thanks!

**Comment by fnord12** [comment]
Are you talking about the alternate color block option under Visuals in settings?   You just put a comma-separated list of the channels in the input box(es).   To change the color of the blocks, you have to manually edit the images in \resources\skins\default\media\pstvButtonNoFocusAlt3.png (or the Estuary version if you're using that skin).   I don't know what "color code" you might have found online, it might be referring to some other version of PsTV that has a different feature.

**Comment by XeXoasz** [comment]
> Are you talking about the alternate color block option under Visuals in settings?   You just put a comma-separated list of the channels in the input box(es).   To change the color of the blocks, you have to manually edit the images in \resources\skins\default\media\pstvButtonNoFocusAlt3.png (or the Estuary version if you're using that skin).   I don't know what "color code" you might have found online, it might be referring to some other version of PsTV that has a different feature.

Ah I was confused thought the number with the commas were color codes. Just tried what you suggested and it works

**Comment by fnord12** [comment]
Excellent.
