### ISSUE TITLE
After just installing the addon, it freezes on updating channels while "reading movie data"

### ISSUE THREAD

**Issue by undecomposed** [fnord12/script.pseudotv#6]
I uninstalled the previous version I have got, and yesterday installed the most recent version. I uninstalled the addon and cleared data. Now, when the addon is starting, it freezes on "reading movie data" while updating channels. I have left it for over 8 hours, and it's still on the same update position.

What logs can I upload here to troubleshoot this?

**Comment by fnord12** [comment]
Hi, i've created this doc to help with reporting issues to me.  I see you already tried clearing the addon/userdata, so if you can just link to to a debug log, i will try to help.

https://github.com/fnord12/script.pseudotv/blob/master/Troubleshooting.md

**Comment by fnord12** [comment]
Please also see issue #4.  If you're using directory channels make sure you have the latest latest version.

**Comment by fnord12** [comment]
undecomposed, i ran into your issue.  Latest build has the fix.  Sorry about that.

**Comment by undecomposed** [comment]
@fnord12 confirmed, this seems to be working like a charm. Thank you!
