### ISSUE TITLE
Lag in new version

### ISSUE THREAD

**Issue by gonzo90017** [fnord12/script.pseudotv#8]
Just upgraded to 2.5.0. Scrolling through the channels now seems very laggy. I now you mentioned that you made a change that might have caused this. Well you were right.

**Comment by gonzo90017** [comment]
Think I found the issue. I usually set **Time between channel resets** to **Never** . I had it set to automatic and that's what was causing the lag.

**Comment by fnord12** [comment]
I'm glad that resolved the lag for you, but the **Time between channel resets** setting shouldn't affect the EPG as far as i know.  I guess if you had such a small number of shows that it was constantly having to reload.  But normally that's a hit you take at startup and that's it.  The main drag on the EPG will be the number of blocks that it has to render (as you noted in the other issue).
