### ISSUE TITLE
Hide Short Videos

### ISSUE THREAD

**Issue by gonzo90017** [fnord12/script.pseudotv#9]
This is a feature request. I'm making some music video channels. Since most of this videos are only a few minutes long. I would prefer to hide them and just have one long generic name on that channel. Say Music Videos or something. This way the guide would look a lot cleaner. 

Also, don't know if it's just me but when there are that many short videos. The guide seems too lag a bit more then usual?

This is what it looks like now:
![Before](https://user-images.githubusercontent.com/24837361/83847835-c9a2a580-a6c1-11ea-9dae-538ca20d7de7.PNG)

This is what I would prefer it look like:
![After](https://user-images.githubusercontent.com/24837361/83847903-e5a64700-a6c1-11ea-981a-6c7aae19c76f.png)

**Comment by fnord12** [comment]
This is a good idea and was in line with some things i was already working on, so it's delivered in 4.5.1.

I've left 4.5.1 as a separate branch right now, to see if any bugs shake out that i didn't catch.  This allows the master branch to serve as a stable release.  But if you want to check it out, grab the branch zip.

**Comment by gonzo90017** [comment]
Hide short music videos is working great. For those wondering which setting it is:
**Don't display individual blocks for these channels**. 
Just type in the channel number. If adding more then one channel, separate with a coma
